# -*- coding: utf-8 -*-
"""Assorted:224_6c_Resnet50_ImageNet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15gGnHfPq5qWWWiJIiwHepgY1GJNgk5Wv
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
model=tf.keras.models.load_model('/content/drive/My Drive/db/Bipartite_Adam/ResNet50_6c_ImgNet')

import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
#test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(preprocessing_function=tf.keras.applications.resnet50.preprocess_input)

test_datagen = ImageDataGenerator()

test_generator = test_datagen.flow_from_directory(
        '/content/drive/My Drive/db/ImgNet/test/',
        classes=['cats','dogs','ships','bikes','tractors','wagons'], 
        target_size=(374, 374),#The target_size is the size of your input images,every image will be resized to this size
        batch_size=32,
        class_mode='categorical')

history=model.evaluate(
test_generator    
)

print(history)